<?php

namespace ATKS\AdminBundle\Repository;

/**
 * FbInterrogatoireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FbInterrogatoireRepository extends \Doctrine\ORM\EntityRepository
{
  public function nbreInterrogatoire() {
      return $this->createQueryBuilder("h")
                      ->select("COUNT(h)")
                      ->getQuery()
                      ->getSingleScalarResult();
  }
}
