<?php

namespace ATKS\AdminBundle\Repository;

/**
 * FbUserAskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FbUserAskRepository extends \Doctrine\ORM\EntityRepository
{
}
