<?php

namespace ATKS\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HopitalUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HopitalUserRepository extends EntityRepository
{
    public function nbreHopital() {
        return $this->createQueryBuilder("h")
                        ->select("COUNT(h)")
                        ->getQuery()
                        ->getSingleScalarResult();
    }
    
    public function nbreHopitauxUserNonVu() {
        return $this->createQueryBuilder("p")
                        ->select("COUNT(p)")
                        ->where("p.vue = :false")
                        ->setParameter("false", false)
                        ->getQuery()
                        ->getSingleScalarResult();
    }
}
