<?php

namespace ATKS\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HopitalServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HopitalServiceRepository extends EntityRepository {

    public function hopitauxServiceRechercher($query) {
        return $this->createQueryBuilder("hs")
                        ->leftJoin("hs.service", "s")
                        ->where("s.nom LIKE :query OR s.tags LIKE :query")
                        ->setParameter("query", '%' . $query . '%')
                        ->getQuery()
                        ->getResult();
    }

    public function nbreServiceHopital($id) {
        return $this->createQueryBuilder("p")
                        ->select("COUNT(p)")
                        ->leftJoin("p.hopital", "h")
                        ->where("h.id = :id")
                        ->setParameter("id", $id)
                        ->getQuery()
                        ->getSingleScalarResult();
    }

}
