<?php

namespace ATKS\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PharmacieUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PharmacieUserRepository extends EntityRepository
{
    public function nbrePharmacie() {
        return $this->createQueryBuilder("p")
                        ->select("COUNT(p)")
                        ->getQuery()
                        ->getSingleScalarResult();
    }
    
     public function nbrePharmaciesUserNonVue() {
        return $this->createQueryBuilder("p")
                        ->select("COUNT(p)")
                        ->where("p.vue = :false")
                        ->setParameter("false", false)
                        ->getQuery()
                        ->getSingleScalarResult();
    }
}
