<?php

namespace ATKS\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PharmacieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PharmacieRepository extends EntityRepository
{
    public function nbrePharmacie() {
        return $this->createQueryBuilder("p")
                        ->select("COUNT(p)")
                        ->getQuery()
                        ->getSingleScalarResult();
    }
}
