<?php

namespace ATKS\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VisiteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisiteurRepository extends EntityRepository
{
    public function nbreVisiteurNonVu() {
        return $this->createQueryBuilder("v")
                        ->select("COUNT(v)")
                        ->where("v.vue = :false")
                        ->setParameter("false", false)
                        ->getQuery()
                        ->getSingleScalarResult();
    }
    
    public function nbreVisiteur() {
        return $this->createQueryBuilder("p")
                        ->select("COUNT(p)")
                        ->getQuery()
                        ->getSingleScalarResult();
    }
}
